apiVersion: v1
kind: Service
metadata:
  name: insecure-bank-ap-service
  namespace: insecure-bank-dev
spec:
  selector:
    app: insecure-bank-ap
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
